source("./setup.R")

source("R/xbb_helper_functions.R")
source("R/07_read_cleaned_neut_data.R")
source("R/08_combine_data_by_immunogen.R")
source("R/08_combine_with_ancestral_data.R")
source("R/08_plotting_helper_functions.R")
source("R/11_helper_plot_functions_manuscript.R")
source("R/11_mixed_effects_modelling_helper_functions.R")
source("R/plot_combining_helper_function.R")
source("R/15_getOR.R")
source("R/17_manuscript_text_helper_functions.R")
source("R/18_generate_dummy_data.R")

source("./processing/07_import_cleaned_data.R")
source("./processing/08_generate_mle_dataset.R")
source("./processing/08a_generate_long_comp_mle_dataset.R")
source("./processing/09_generate_efficacy_dataset.R")
source("./processing/11_setup_mixed_effects_modelling.R")
source("./processing/12_setup_plotting_variables.R")

source("./analysis/09_make_efficacy_plots_from_regressions.R")
source("./analysis/14_run_all_mixed_effects_models.R")
source("./analysis/17_manuscript_text_final.R")
source("./analysis/18_manuscript_plots_final.R")